name: Shellcheck

on:
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scripts/**'

permissions:
  contents: read

jobs:
  shellcheck:
    name: Lint shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts'
          severity: warning
